const eng = [
    "Designation", 
    "Employ", 
    "Imply", 
    "Frantic", 
    "Delimit", 
    "Percive", 
    "Breeding Ground", 
    "Decline", 
    "Impuity", 
    "Reveal", 
    "Durable", 
    "Deteriorate", 
    "On one hand", 
    "Breeding", 
    "Oversight", 
    "Embezzlement", 
    "Have recently done so", 
    "On the other hand", 
    "Siphoning", 
    "Uphold", 
    "Sufficient", 
    "Timely", 
    "Rigorous", 
    "Withholding", 
    "Mandatory", 
    "Register", 
    "Scrutiny", 
    "Clampdown", 
    "Secrecy", 
    "Complicit", 
    "Illicit", 
    "Confiscate", 
    "Despite", 
    "On the flip side", 
    "The rest", 
    "Underlying", 
    "Exert", 
    "Sow", 
    "Divert", 
    "Common", 
    "Discontent", 
    "Coincide", 
    "Disparity", 
    "Outright", 
    "Outbreak", 
    "Misuse", 
    "Deprive", 
    "Erode", 
    "Grievance", 
    "Undermine", 
    "Deprive", 
    "Firm", 
    "Entrench", 
    "Coup", 
    "Dissent", 
    "Plight", 
    "Adept", 
    "Ignite", 
    "Casualty", 
    "Ticked me off", 
    "Ticked me off", 
    "Draw in", 
    "Moneybags", 
    "Unless", 
    "Pleasant", 
    "Bathrobe", 
    "Unravel", 
    "Catch up", 
    "Standstill", 
    "Landscape", 
    "Undue", 
    "Safeguard", 
    "Restriction", 
    "Dilute", 
    "Watchdog", 
    "Intertwine", 
    "Pervasive", 
    "Unrest", 
    "Consecutive", 
    "Lack", 
    "Decisive", 
    "Imposed", 
    "Vicious", 
    "Spark", 
    "Sparked", 
    "Impose", 
    "Dismantle"    
];

const bhs = [
    "An official title or name (noun)", 
    "To have someone work or do a job for you and pay them for it (verb)", 
    "To communicate an idea or feeling without saying it directly (verb)", 
    "Almost out of control because of extreme emotion; such as worry (adjective)", 
    "To mark or describe the limits of something (verb)", 
    "See (verb)", 
    "A place where animals breed and produce their babies (noun)", 
    "Go down (verb)", 
    "Impuitas", 
    "To make known or show something that is surprising or that was previously secret (verb)", 
    "Able to last a long time without becoming damaged (adjective)", 
    "To become worse (verb)", 
    "Di satu sisi", 
    "Reproduce (verb)", 
    "A mistake made because of a failure to notice something (noun)", 
    "To secretly take money that is in your care or that belongs to an organization or business you work for (noun)", 
    "Baru -baru ini melakukannya", 
    "Di samping itu", 
    "Menyedot", 
    "To defend or keep a principle or law (verb)", 
    "Enough for a particular purpose (adjective)", 
    "Happening at a suitable moment (adjective)", 
    "Careful to look at or consider every part of something to make certain it is correct or safe (adjective)", 
    "Pemotongan", 
    "Describes something that must be done; or is demanded by law (adjective)", 
    "Put on list (verb)", 
    "The careful and detailed examination of something in order to get information about it (noun)", 
    "A sudden action taken by a government or people in authority to stop or limit a particular activity (noun)", 
    "The state of being secret or of keeping something secret (noun)", 
    "Involved in or knowing about a crime or some activity that is wrong (adjective)", 
    "Illegal or disapproved of by society (noun)", 
    "To take a possession away from someone when you have the right to do so; usually as a punishment and often for a limited period; after which it is returned to the owner (noun)", 
    "Meskipun", 
    "Di sisi lain", 
    "Sisanya", 
    "Based on (adjective)", 
    "To use something such as authority; power; influence; etc. In order to make something happen (verb)", 
    "To put seeds in or on the ground so that plants will grow (verb)", 
    "To take someone's attention away from something (verb)", 
    "Usual (adjective)", 
    "A feeling of wanting better treatment or an improved situation (noun)", 
    "To happen at or near the same time (verb)", 
    "A lack of equality or similarity; especially in a way that is not fair (noun)", 
    "Sekaligus", 
    "A time when something suddenly begins; especially a disease or something else dangerous or unpleasant (noun)", 
    "To use something in an unsuitable way or in a way that was not intended (verb)", 
    "To take something; especially something necessary or pleasant; away from someone (verb)", 
    "Damage physically (verb)", 
    "A complaint or a strong feeling that you have been treated unfairly (noun)", 
    "To make someone less confident; less powerful; or less likely to succeed; or to make something weaker; often gradually (verb)", 
    "To take something; especially something necessary or pleasant; away from someone (verb)", 
    "Forceful (adjective)", 
    "To firmly establish something; especially an idea or a problem; so that it cannot be changed (verb)", 
    "A sudden illegal; often violent; taking of government power; especially by part of an army (noun)", 
    "Strong difference of opinion on a particular subject; especially about an official suggestion or plan or a popular belief (noun)", 
    "An unpleasant condition; especially a serious; sad; or difficult one (noun)", 
    "Having a natural ability to do something that needs skill (adjective)", 
    "Start burning or explode (verb)", 
    "A person injured or killed in a serious accident or war (noun)", 
    "To speak severely to and criticize someone who has done (UK Informal)", 
    "Annoy ; to annoy someone (US Informal)", 
    "Darkness & becoming dark (pharsal verb)", 
    "A rich person (noun)", 
    "Except if (conjuction)", 
    "enjoyable;attractive;friendly or easy to like (adjective)", 
    "a loose piece of clothing like a coat; usually made of thick towelling material; worn informally inside the house; especially before or after a bath (noun)", 
    "If a piece of knitted or woven cloth; a knot; or a mass of thread unravels; it separates into a single thread; and if you unravel it; you separate it into a single thread (verb)", 
    "a meeting or conversation in which people discuss what has happened since the last time that they met (noun)", 
    "A condition in which all movement or activity has stopped (noun)", 
    "a large area of land; especially in relation to its appearance (noun", 
    "To a level that is more than is necessary; acceptable; or reasonable (adjective)", 
    "To protect something from harm (verb)", 
    "an official limit on something (noun)", 
    "Tmake a liquid weaker by mixing in something else (noun)", 
    "a person or organization responsible for making certain that companies obey particular standards and do not act illegally (noun)", 
    "to twist or be twisted together; or to be connected so as to be difficult to separate (verb)", 
    "present or noticeable in every part of a thing or place (adjective)", 
    "Disagreements or fighting between different groups of people (noun)", 
    "Consecutive events; numbers; etc. follow one after another without an interruption (adjective)", 
    "The fact that something is not available or that there is not enough of it (noun)", 
    "Able to make decisions quickly and confidently; or showing this quality (adjective)", 
    "To officially force a rule; tax; punishment; etc. to be obeyed or received (verb)", 
    "Vicious people or actions show an intention or wish to hurt someone or something very badly (adjective)", 
    "a very small piece of fire that flies out from something that is burning; or one that is made by rubbing two hard things together; or a flash of light made by electricity (noun)", 
    "Dipicu", 
    "Memaksakan", 
    "to take a machine apart or to come apart into separate pieces (verb)"    
];