const eng = [
    "Designation",
    "Employ",
    "Imply",
    "Frantic",
    "Delimit",
    "Percive",
    "Breeding Ground",
    "Decline",
    "Impuity",
    "Reveal",
    "Durable",
    "Deteriorate",
    "On one hand",
    "Breeding",
    "Oversight",
    "Embezzlement",
    "Have recently done so",
    "On the other hand",
    "Siphoning",
    "Uphold",
    "Sufficient",
    "Timely",
    "Rigorous",
    "Withholding",
    "Mandatory",
    "Register",
    "Scrutiny",
    "Clampdown",
    "Secrecy",
    "Complicit",
    "Illicit",
    "Confiscate",
    "Despite",
    "On the flip side",
    "The rest",
    "Underlying",
    "Exert",
    "Sow",
    "Divert",
    "Common",
    "Discontent",
    "Coincide",
    "Disparity",
    "Outright",
    "Outbreak",
    "Misuse",
    "Deprive",
    "Erode",
    "Grievance",
    "Undermine",
    "Deprive",
    "Firm",
    "Entrench",
    "Coup",
    "Dissent",
    "Plight",
    "Adept",
    "Ignite",
    "Casualty"

];

const bhs = [
    "An official title or name (noun)", 
    "To have someone work or do a job for you and pay them for it (verb)", 
    "To communicate an idea or feeling without saying it directly (verb)", 
    "Almost out of control because of extreme emotion/ such as worry (adjective)", 
    "To mark or describe the limits of something (verb)", 
    "See (verb)", 
    "A place where animals breed and produce their babies (noun)", 
    "Go down (verb)", 
    "Impuitas", 
    "To make known or show something that is surprising or that was previously secret (verb)", 
    "Able to last a long time without becoming damaged (adjective)", 
    "To become worse (verb)", 
    "Di satu sisi", 
    "Reproduce (verb)", 
    "A mistake made because of a failure to notice something (noun)", 
    "To secretly take money that is in your care or that belongs to an organization or business you work for (noun)", 
    "Baru -baru ini melakukannya", 
    "Di samping itu", 
    "Menyedot", 
    "To defend or keep a principle or law (verb)", 
    "Enough for a particular purpose (adjective)", 
    "Happening at a suitable moment (adjective)", 
    "Careful to look at or consider every part of something to make certain it is correct or safe (adjective)", 
    "Pemotongan", 
    "Describes something that must be done/ or is demanded by law (adjective)", 
    "Put on list (verb)", 
    "The careful and detailed examination of something in order to get information about it (noun)", 
    "A sudden action taken by a government or people in authority to stop or limit a particular activity (noun)", 
    "The state of being secret or of keeping something secret (noun)", 
    "Involved in or knowing about a crime or some activity that is wrong (adjective)", 
    "Illegal or disapproved of by society (noun)", 
    "To take a possession away from someone when you have the right to do so/ usually as a punishment and often for a limited period/ after which it is returned to the owner (noun)", 
    "Meskipun", 
    "Di sisi lain", 
    "Sisanya", 
    "Based on (adjective)", 
    "To use something such as authority/ power/ influence/ etc. In order to make something happen (verb)", 
    "To put seeds in or on the ground so that plants will grow (verb)", 
    "To take someone's attention away from something (verb)", 
    "Usual (adjective)", 
    "A feeling of wanting better treatment or an improved situation (noun)", 
    "To happen at or near the same time (verb)", 
    "A lack of equality or similarity/ especially in a way that is not fair (noun)", 
    "Sekaligus", 
    "A time when something suddenly begins/ especially a disease or something else dangerous or unpleasant (noun)", 
    "To use something in an unsuitable way or in a way that was not intended (verb)", 
    "To take something/ especially something necessary or pleasant/ away from someone (verb)", 
    "Damage physically (verb)", 
    "A complaint or a strong feeling that you have been treated unfairly (noun)", 
    "To make someone less confident/ less powerful/ or less likely to succeed/ or to make something weaker/ often gradually (verb)", 
    "To take something/ especially something necessary or pleasant/ away from someone (verb)", 
    "Forceful (adjective)", 
    "To firmly establish something/ especially an idea or a problem/ so that it cannot be changed (verb)", 
    "A sudden illegal/ often violent/ taking of government power/ especially by part of an army (noun)", 
    "Strong difference of opinion on a particular subject/ especially about an official suggestion or plan or a popular belief (noun)", 
    "An unpleasant condition/ especially a serious/ sad/ or difficult one (noun)", 
    "Having a natural ability to do something that needs skill (adjective)", 
    "Start burning or explode (verb)", 
    "A person injured or killed in a serious accident or war (noun)"
    
];