const eng = [
    "Designation", 
    "Employed", 
    "Imply", 
    "Franties", 
    "Delimitation", 
    "Percive", 
    "Breeding Ground", 
    "Decline", 
    "Impuity", 
    "Reveal", 
    "Durable", 
    "Deteriorate", 
    "On one hand", 
    "Breeding", 
    "Oversight", 
    "Embezzlement", 
    "Experiencing", 
    "Have recently done so", 
    "On the other hand", 
    "Siphoning", 
    "Uphold", 
    "Sufficient", 
    "Timely", 
    "Rigorous", 
    "Withholding", 
    "Mandatory", 
    "Register", 
    "Scrutiny", 
    "Clamp down", 
    "Secrecy", 
    "Complicit", 
    "Illicit", 
    "Confiscate", 
    "Despite", 
    "On the flip side", 
    "The rest", 
    "Underlying", 
    "Exert", 
    "Sow", 
    "Divert", 
    "Common", 
    "Discontent", 
    "Coincide", 
    "Disparity", 
    "Outright", 
    "Outbreak", 
    "Misuse", 
    "Deprive", 
    "Eroding", 
    "Grievance", 
    "Undermining", 
    "Deprive", 
    "Firm", 
    "Entrenched", 
    "Coup", 
    "Dissenter", 
    "Plight", 
    "Adept", 
    "Ignite", 
    "Casualty"    
];

const bhs = [
    "Penamaan", 
    "Dipekerjakan", 
    "Menyiratkan", 
    "Kegilaan", 
    "Pembatasan", 
    "Melihat", 
    "Tempat berkembang biak", 
    "Menolak", 
    "Impuitas", 
    "Mengungkap", 
    "Tahan lama", 
    "Memburuk", 
    "Di satu sisi", 
    "Pembiakan", 
    "Kelalaian", 
    "Penggelapan", 
    "Mengalami", 
    "Baru -baru ini melakukannya", 
    "Di samping itu", 
    "Menyedot", 
    "Menegakkan", 
    "Memadai", 
    "Tepat waktu", 
    "Keras", 
    "Pemotongan", 
    "Wajib", 
    "Daftar", 
    "Pengawasan", 
    "Melarang", 
    "Kerahasiaan", 
    "Terlibat", 
    "Dilarang", 
    "Menyita", 
    "Meskipun", 
    "Di sisi lain", 
    "Sisanya", 
    "Yang mendasarinya", 
    "Menggunakan", 
    "Menabur", 
    "Mengalihkan", 
    "Umum", 
    "Ketidakpuasan", 
    "Bertepatan", 
    "Perbedaan", 
    "Sekaligus", 
    "Wabah", 
    "Penyalahgunaan", 
    "Mencabut", 
    "Mengikis", 
    "Keluhan", 
    "Meremehkan", 
    "Mencabut", 
    "Tegas", 
    "Mengakar", 
    "Kudeta", 
    "Orang ingkar", 
    "Nasib buruk", 
    "Mahir", 
    "Menyalakan", 
    "Korban"
    
];